apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:
  app: dcaas
resources:
- ../../../../../generators/dcaas
- ../../../../../generators/redis
- configs
- secrets
transformers:
- ../secrets
- ../configs
- values.yaml
- redisvalues.yaml
