apiVersion: qlik.com/v1
kind: EnvUpsert
metadata:
  name: engineEnvUpdate-keysUri
  labels:
    key: keysUri
enabled: true
target:
  kind: Engine
  name: engine-reload
path: spec/podSpec/containers/env
env:
  - name: KEYS_URI
    valueFrom:
      configMapKeyRef:
        key: keysUri
        name: configs
