apiVersion: apps/v1
kind: Deployment
metadata:
  name: edge-auth
spec:
  template:
    metadata:
      labels:
        edge-auth-nats-client: null
    spec:
      volumes:
      - name: edge-auth
        secret:
          secretName: edge-auth-secrets
          items:
            - key: tokenAuthPrivateKey
              path: jwtPrivateKey
            - key: tokenAuthPrivateKeyId
              path: jwtPublicKeys
            - key: cookiesKeys
              path: cookieKeys
            - key: loginStateKey
              path: loginStateKey
      containers:
      - name: main
        imagePullPolicy: IfNotPresent
        env:
        - name: USERS_URI
          valueFrom:
            configMapKeyRef:
              key: usersUri
              name: edge-auth-configs
        - name: TENANTS_URI
          valueFrom:
            configMapKeyRef:
              key: tenantsUri
              name: edge-auth-configs
        - name: NATS_URI
          valueFrom:
            configMapKeyRef:
              key: natsUri
              name: edge-auth-configs
        - name: NATS_STREAMING_CLUSTER_ID
          valueFrom:
            configMapKeyRef:
              key: natsStreamingClusterId
              name: edge-auth-configs
        - name: MONGODB_URI
          valueFrom:
            secretKeyRef:
              key: mongoDbUri
              name: edge-auth-secrets
        - name: KEYS_URI
          valueFrom:
            configMapKeyRef:
              key: keysUri
              name: edge-auth-configs
        - name: IDENTITY_PROVIDERS_V1_URI
          valueFrom:
            configMapKeyRef:
              key: identityProvidersV1Uri
              name: edge-auth-configs
        - name: IDENTITY_PROVIDERS_URI
          valueFrom:
            configMapKeyRef:
              key: identityProvidersUri
              name: edge-auth-configs
        - name: GROUPS_URI
          valueFrom:
            configMapKeyRef:
              key: groupsUri
              name: edge-auth-configs
        - name: FEATURE_FLAGS_URI
          valueFrom:
            configMapKeyRef:
              key: featureFlagsUri
              name: edge-auth-configs
        - name: CORS_URI
          valueFrom:
            configMapKeyRef:
              key: corsUri
              name: edge-auth-configs
        - $patch: delete
          name: MONGO_URI
        - name: MONGO_URI
          value: $(MONGODB_URI)
        - $patch: delete
          name: FEATURE_FLAGS_URI
        - name: FEATURES_RESOURCE
          value: $(FEATURE_FLAGS_URI)/v1
        - $patch: delete
          name: IDENTITY_PROVIDERS_RESOURCE
        - name: IDENTITY_PROVIDERS_RESOURCE
          value: $(IDENTITY_PROVIDERS_URI)
        - $patch: delete
          name: IDENTITY_PROVIDERS_EXT_RESOURCE
        - name: IDENTITY_PROVIDERS_EXT_RESOURCE
          value: $(IDENTITY_PROVIDERS_V1_URI)
        - $patch: delete
          name: USERS_RESOURCE
        - name: USERS_RESOURCE
          value: $(USERS_URI)
        - $patch: delete
          name: TENANTS_RESOURCE
        - name: TENANTS_RESOURCE
          value: $(TENANTS_URI)
        - $patch: delete
          name: GROUPS_RESOURCE
        - name: GROUPS_RESOURCE
          value: $(GROUPS_URI)/v1
        - $patch: delete
          name: KEYS_RESOURCE
        - name: KEYS_RESOURCE
          value: $(KEYS_URI)
        - $patch: delete
          name: CORS_RESOURCE
        - name: CORS_RESOURCE
          value: $(CORS_URI)
        - $patch: delete
          name: NATS_URL
        - name: NATS_URL
          value: $(NATS_URI)
        - $patch: delete
          name: NATS_CLUSTER_ID
        - name: NATS_CLUSTER_ID
          value: $(NATS_STREAMING_CLUSTER_ID)
      - name: oidc
        imagePullPolicy: IfNotPresent
        env:
        - $patch: delete
          name: REDIRECTS
        - name: OIDC_REDIRECT_URI
          valueFrom:
            configMapKeyRef:
              key: oidcRedirectUri
              name: edge-auth-configs
        - name: REDIRECTS
          value: $(OIDC_REDIRECT_URI)
