apiVersion: qlik.com/v1
kind: SearchReplace
metadata:
  name: all-prefix
target:
  labelSelector: app=elastic-infra
path: /
search: \$\(PREFIX\)
replaceWithObjRef:
  objref:
    apiVersion: v1
    kind: ConfigMap
  fieldref:
    fieldpath: metadata.labels.release
