apiVersion: qlik.com/v1
kind: EnvUpsert
metadata:
  name: engineEnvUpdate-dcaasUri
  labels:
    key: dcaasUri
enabled: true
target:
  kind: Engine
  name: engine-reload
path: spec/podSpec/containers/env
env:
- name: DCAAS_URI
  valueFrom:
    configMapKeyRef:
      key: dcaasUri
      name: configs
