apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:
  app: chronos
resources:
- ../../../../../generators/chronos
- secrets
- configs
transformers:
- ../secrets
- ../configs
- values.yaml

