apiVersion: qlik.com/v1
kind: EnvUpsert
metadata:
  name: engineEnvUpdate-encryptionUri
  labels:
    key: encryptionUri
enabled: true
target:
  kind: Engine
  name: engine-reload
path: spec/podSpec/containers/env
env:
- name: ENCRYPTION_URI
  valueFrom:
    configMapKeyRef:
      key: encryptionUri
      name: configs
