apiVersion: apps/v1
kind: Deployment
metadata:
  name: quotas
spec:
  template:
    metadata:
      labels:
        quotas-nats-client: null
    spec:
      containers:
      - name: main
        imagePullPolicy: IfNotPresent
        env:
        - $patch: delete
          name: AUTH_JWKS_URI
        - name: KEYS_URI
          valueFrom:
            configMapKeyRef:
              key: keysUri
              name: quotas-configs
        - name: AUTH_JWKS_URI
          value: $(KEYS_URI)/keys/qlik.api.internal
        - $patch: delete
          name: SERVICE_JWT_PRIVATE_KEY
        - name: TOKEN_AUTH_PRIVATE_KEY
          valueFrom:
            secretKeyRef:
              key: tokenAuthPrivateKey
              name: quotas-secrets
        - name: SERVICE_JWT_PRIVATE_KEY
          value: $(TOKEN_AUTH_PRIVATE_KEY)
        - $patch: delete
          name: SERVICE_JWT_KEY_ID
        - name: TOKEN_AUTH_PRIVATE_KEY_ID
          valueFrom:
            secretKeyRef:
              key: tokenAuthPrivateKeyId
              name: quotas-secrets
        - name: SERVICE_JWT_KEY_ID
          value: $(TOKEN_AUTH_PRIVATE_KEY_ID)
        - $patch: delete
          name: INTERNAL_TOKENS_URI
        - name: TOKEN_AUTH_URI
          valueFrom:
            configMapKeyRef:
              key: tokenAuthUri
              name: quotas-configs
        - name: INTERNAL_TOKENS_URI
          value: $(TOKEN_AUTH_URI)/v1/internal-tokens
        - $patch: delete
          name: LICENSES_URI
        - name: LICENSES_URI
          valueFrom:
            configMapKeyRef:
              key: licensesUri
              name: quotas-configs
        - $patch: delete
          name: SPACES_URI
        - name: SPACES_URI
          valueFrom:
            configMapKeyRef:
              key: spacesUri
              name: quotas-configs
        #null value causing issue so deleting it
        - $patch: delete
          name: ENVIRONMENT