apiVersion: qlik.com/v1
kind: SelectivePatch
metadata:
  name: redis-component-configs
enabled: true
patches:
- target:
    kind: SuperConfigMap
  patch: |-
    apiVersion: qlik.com/v1
    kind: SuperConfigMap
    metadata:
      name: redis-configs
    data:
      redisUri: $(PREFIX)-redis-master:6379