apiVersion: apps/v1
kind: Deployment
metadata:
  name: qix-data-connection
spec:
  template:
    metadata:
      labels:
        qix-data-connection-nats-client: null
    spec:
      volumes:
      - name: qdc-storage
        secret:
          secretName: qix-data-connection-secrets
          items:
            - key: tokenAuthPrivateKey
              path: jwtPrivateKey
      containers:
      - name: main
        imagePullPolicy: IfNotPresent
        env:
        - name: MONGODB_URI
          valueFrom:
            secretKeyRef:
              key: mongoDbUri
              name: qix-data-connection-secrets
        - $patch: delete
          name: JWKS_ENDPOINT
        - name: KEYS_URI
          valueFrom:
            configMapKeyRef:
              key: keysUri
              name: qix-data-connection-configs
        - name: JWKS_ENDPOINT
          value: $(KEYS_URI)/keys/qlik.api.internal
        - $patch: delete
          name: E2S_ADDR
        - name: ENCRYPTION_URI
          valueFrom:
            configMapKeyRef:
              key: encryptionUri
              name: qix-data-connection-configs
        - name: E2S_ADDR
          value: $(ENCRYPTION_URI)
        - $patch: delete
          name: SPACE_URI
        - name: SPACES_URI
          valueFrom:
            configMapKeyRef:
              key: spacesUri
              name: qix-data-connection-configs
        - $patch: delete
          name: AUTH_URI
        - name: TOKEN_AUTH_URI
          valueFrom:
            configMapKeyRef:
              key: tokenAuthUri
              name: qix-data-connection-configs
        - name: AUTH_URI
          value: $(TOKEN_AUTH_URI)
        - $patch: delete
          name: QIX_DATAFILES_URI
        - name: QIX_DATA_FILES_URI
          valueFrom:
            configMapKeyRef:
              key: qixDataFilesUri
              name: qix-data-connection-configs
        - name: QIX_DATAFILES_URI
          value: $(QIX_DATA_FILES_URI)
        - $patch: delete
          name: KEY_ID
        - name: TOKEN_AUTH_PRIVATE_KEY_ID
          valueFrom:
            secretKeyRef:
              key: tokenAuthPrivateKeyId
              name: qix-data-connection-secrets
        - name: KEY_ID
          value: $(TOKEN_AUTH_PRIVATE_KEY_ID)
        - $patch: delete
          name: MONGO_URI
        - name: MONGO_URI
          value: $(MONGODB_URI)
