apiVersion: qlik.com/v1
kind: EnvUpsert
metadata:
  name: engineEnvUpdate-qixDataConnectionUri
  labels:
    key: qixDataConnectionUri
enabled: true
target:
  kind: Engine
  name: engine-reload
path: spec/podSpec/containers/env
env:
- name: QIX_DATA_CONNECTION_URI
  valueFrom:
    configMapKeyRef:
      key: qixDataConnectionUri
      name: configs
