apiVersion: qlik.com/v1
kind: EnvUpsert
metadata:
  name: engineEnvUpdate-acceptEULA
  labels:
    key: acceptEULA
enabled: true
target:
  kind: Engine
  name: engine-reload
path: spec/podSpec/containers/env
env:
  - name: ACCEPT_EULA
    valueFrom:
      configMapKeyRef:
        key: acceptEULA
        name: configs
