apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:
  app: keys
generators:
  - generators
transformers:
  - patches
  - super-configs
  - configs
  #- ../qliksense/generators/secrets 
  - ../qliksense/generators/configs
  - ../../../../.operator/patches
  - ../../../../configuration/patches
images:
  - name: qlik-docker-qsefe.bintray.io/keys
    newName: $(IMAGE_REGISTRY)/keys
