apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:
  app: keys
generators:
  - generators
transformers:
  - all-transformers
images:
  - name: qlik-docker-qsefe.bintray.io/keys
    newName: $(IMAGE_REGISTRY)/keys
