apiVersion: qlik.com/v1
kind: EnvUpsert
metadata:
  name: engineEnvUpdate-featureFlagsUri
  labels:
    key: featureFlagsUri
enabled: true
target:
  kind: Engine
  name: engine-reload
path: spec/podSpec/containers/env
env:
- name: FEATURE_FLAGS_URI
  valueFrom:
    configMapKeyRef:
      key: featureFlagsUri
      name: configs
