apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: qliksense
resources:
  - github.com/qlik-oss/qliksense//values 
patchesStrategicMerge:
  - devmode.yaml
  - acceptEULA.yaml
  - releaseNamespace.yaml
