apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:
  app: data-connector-qwc
generators:
  - generators
transformers:
  - all-transformers
images:
  - name: qlik-docker-qsefe.bintray.io/data-connector-qwc
    newName: $(IMAGE_REGISTRY)/data-connector-qwc
