apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:
  app: keys
resources:
- ../../../../../generators/keys
#- ../../../configs
transformers:
#- ../configs
- values.yaml
#patches:
# - target:
#     kind: SuperSecret
#   patch: |-
#     - op: replace
#       path: /metadata/name
#       value: keys-secrets
# - target:
#     kind: SuperConfigMap
#   patch: |-
#     - op: replace
#       path: /metadata/name
#       value: keys-configs

