apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:
  app: resource-library
resources:
- ../../../../../generators/resource-library
- ../../../secrets
- ../../../configs
transformers:
- ../secrets
- ../configs
- values.yaml 
patches:
- target:
    kind: SuperSecret
  patch: |-
    - op: replace
      path: /metadata/name
      value: resource-library-secrets
- target:
    kind: SuperConfigMap
  patch: |-
    - op: replace
      path: /metadata/name
      value: resource-library-configs
