apiVersion: qlik.com/v1
kind: EnvUpsert
metadata:
  name: engineEnvUpdate-licensesUri
  labels:
    key: licensesUri
enabled: true
target:
  kind: Engine
  name: engine-reload
path: spec/podSpec/containers/env
env:
- name: LICENSES_URI
  valueFrom:
    configMapKeyRef:
      key: licensesUri
      name: configs
