apiVersion: qlik.com/v1
kind: SelectivePatch
metadata:
  name: licensesUri
  labels:
    key: licensesUri
enabled: true
patches:
- target:
    kind: Deployment
  patch: |-
    apiVersion: apps/v1
    kind: Deployment
    metadata:
      name: component
    spec:
      template:
        spec:
          containers:
          - name: main
            env:
            - name: LICENSES_URI
              valueFrom:
                configMapKeyRef:
                  key: licensesUri
                  name: configs
- target:
    kind: ConfigMap
    name: .*-configs
  patch: |-
    apiVersion: v1
    kind: ConfigMap
    metadata:
      name: component-configs
    data:
      licensesUri: null