apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:
  app: elastic-infra
resources:
- ../../../../../generators/elastic-infra
- ../../../secrets
- ../../../configs
transformers:
- ../secrets
- values.yaml
patches:
- target:
    kind: SuperSecret
  patch: |-
    - op: replace
      path: /metadata/name
      value: elastic-infra-secrets
- target:
    kind: SuperConfigMap
  patch: |-
    - op: replace
      path: /metadata/name
      value: elastic-infra-configs