apiVersion: apps/v1
kind: Deployment
metadata:
  name: dcaas
spec:
  template:
    spec:
      containers:
      - name: main
        imagePullPolicy: IfNotPresent
        env:
        - name: SPACES_URI
          valueFrom:
            configMapKeyRef:
              key: spacesUri
              name: dcaas-configs 
        - $patch: delete
          name: SPACE_SERVICE
        - name: SPACE_SERVICE
          value: $(SPACES_URI)
        - name: DCAAS_DATA_CONNECTION_URI
          valueFrom:
            configMapKeyRef:
              key: dcaasDataConnectionUri
              name: dcaas-configs 
        - $patch: delete
          name: NEW_DATA_CONNECTION_SERVICE
        - name: NEW_DATA_CONNECTION_SERVICE
          value: $(DCAAS_DATA_CONNECTION_URI)
        - name: CONNECTOR_SERVICES
          valueFrom:
            configMapKeyRef:
              key: connectorServices
              name: dcaas-configs
        - $patch: delete
          name: CONNECTOR_SERVICE
        - name: CONNECTOR_SERVICE
          value: $(CONNECTOR_SERVICES)
        - name: QIX_DATA_CONNECTION_URI
          valueFrom:
            configMapKeyRef:
              key: qixDataConnectionUri
              name: dcaas-configs
        - $patch: delete
          name: DATA_CONNECTION_SERVICE
        - name: DATA_CONNECTION_SERVICE
          value: $(QIX_DATA_CONNECTION_URI)
        - name: FEATURE_FLAGS_URI
          valueFrom:
            configMapKeyRef:
              key: featureFlagsUri
              name: dcaas-configs
        - $patch: delete
          name: FEATUREFLAG_URL
        - name: FEATUREFLAG_URL
          value: $(FEATURE_FLAGS_URI)
        - name: KEYS_URI
          valueFrom:
            configMapKeyRef:
              key: keysUri
              name: dcaas-configs
        - $patch: delete
          name: JWKS_ENDPOINT
        - name: JWKS_ENDPOINT
          value: $(KEYS_URI)/keys/qlik.api.internal