apiVersion: apps/v1
kind: Deployment
metadata:
  name: resource-library
spec:
  template:
    metadata:
      labels:
        resource-library-nats-client: null
    spec:
      volumes:
      - name: resource-library-secret
        secret:
          secretName: resource-library-secrets
          items:
            - key: tokenAuthPrivateKey
              path: jwtPrivateKey
      containers:
      - name: main
        imagePullPolicy: IfNotPresent
        env:
        - name: NATS_URI
          valueFrom:
            configMapKeyRef:
              key: natsUri
        - name: NATS_STREAMING_CLUSTER_ID
          valueFrom:
            configMapKeyRef:
              key: natsStreamingClusterId
              name: resource-library-configs
        - name: MONGODB_URI
          valueFrom:
            secretKeyRef:
              key: mongoDbUri
              name: resource-library-secrets
        - name: KEYS_URI
          valueFrom:
            configMapKeyRef:
              key: keysUri
              name: resource-library-configs
        - $patch: delete
          name: PDS_URI
        - name: PDS_URI
          valueFrom:
            configMapKeyRef:
              key: pdsUri
              name: resource-library-configs
        #  AUTH_JWKS_URI -> KEYS_URI
        - $patch: delete
          name: AUTH_JWKS_URI
        - name: AUTH_JWKS_URI
          value: $(KEYS_URI)/keys/qlik.api.internal
        - $patch: delete
          name: KEY_ID
        - name: TOKEN_AUTH_PRIVATE_KEY_ID
          valueFrom:
            secretKeyRef:
              key: tokenAuthPrivateKeyId
              name: resource-library-secrets
        - name: KEY_ID
          value: $(TOKEN_AUTH_PRIVATE_KEY_ID)
        - name: TOKEN_AUTH_URI
          valueFrom:
            configMapKeyRef:
              key: tokenAuthUri
              name: resource-library-configs
        - name: INTERNAL_TOKENS_RESOURCE
          value: $(TOKEN_AUTH_URI)/v1
        - name: NATS_SERVERS
          value: $(NATS_URI)
        - $patch: delete
          name: MONGO_URI
        - name: MONGO_URI
          value: $(MONGODB_URI)
        - $patch: delete
          name: NATS_URL
        - name: NATS_URL
          value: $(NATS_URI)
        - $patch: delete
          name: NATS_CLUSTER_ID
        - name: NATS_CLUSTER_ID
          value: $(NATS_STREAMING_CLUSTER_ID)
