apiVersion: qlik.com/v1
kind: SelectivePatch
metadata:
  name: resource-library
enabled: true
patches:
- path: deploymentJSON.yaml
  target:
    kind: Deployment
    name: resource-library
- path: deployment.yaml
