apiVersion: apps/v1
kind: Deployment
metadata:
  name: encryption
spec:
  template:
    spec:
      containers:
      - name: main
        imagePullPolicy: IfNotPresent
        env:
        - $patch: delete
          name: AUTH_JWKS_URI
        - name: AUTH_JWKS_URI
          value: $(KEYS_URI)/keys/qlik.api.internal