apiVersion: qlik.com/v1
kind: SelectivePatch
metadata:
  name: encryption
enabled: true
patches:
  - path: deploymentJSON.yaml
    target:
      kind: Deployment
      name: encryption
  - path: deployment.yaml
