apiVersion: builtin
kind: PatchTransformer
metadata:
  name: qliksense-engine
target:
  kind: Engine
patch: |-
  kind: Engine
  metadata:
    name: component
  spec:
    metadata:
      labels:
        qliksense-messaging-nats-client: "true"

