apiVersion: qlik.com/v1
kind: EnvUpsert
metadata:
  name: engineEnvUpdate-natsUri
  labels:
    key: natsUri
enabled: true
target:
  kind: Engine
  name: engine-reload
path: spec/podSpec/containers/env
env:
- name: NATS_URI
  valueFrom:
    configMapKeyRef:
      key: natsUri
      name: configs
