apiVersion: qlik.com/v1
kind: SelectivePatch
metadata:
  name: natsUri
  labels:
    key: natsUri
enabled: true
patches:
- target:
    kind: Deployment
  patch: |-
    apiVersion: apps/v1
    kind: Deployment
    metadata:
      name: component
    spec:
      template:
        spec:
          containers:
          - name: main
            env:
            - name: NATS_URI
              valueFrom:
                configMapKeyRef:
                  key: natsUri
                  name: configs
- target:
    kind: StatefulSet
  patch: |-
    apiVersion: apps/v1
    kind: StatefulSet
    metadata:
      name: component
    spec:
      template:
        spec:
          containers:
          - name: main
            env:
            - name: NATS_URI
              valueFrom:
                configMapKeyRef:
                  key: natsUri
                  name: configs
- target:
    kind: ConfigMap
    name: .*-configs
  patch: |-
    apiVersion: v1
    kind: ConfigMap 
    metadata:
      name: component-configs
    data:
      natsUri: null
