apiVersion: qlik.com/v1
kind: SelectivePatch
metadata:
  name: pvcClientCertificates
  labels:
    key: pvcClientCertificates
enabled: false
patches:
- target:
    kind: Deployment
  patch: |-
    apiVersion: apps/v1
    kind: Deployment
    metadata:
      name: component
    spec:
      template:
        spec:
          containers:
          - name: main
            volumeMounts:
            - name: ca-certificates
              mountPath: "/etc/ssl/certs"
          volumes:
          - name: ca-certificates
            persistentVolumeClaim:
              claimName: $(CERT_PVC) 
- target:
    kind: Secret
    name: .*-secrets
  patch: |-
    apiVersion: v1
    kind: Secret
    metadata:
      name: component-secrets
    stringData:
      mongoDbUri: null
