varReference:
- path: metadata/annotations/nginx.ingress.kubernetes.io\/auth-url
  kind: Ingress
- path: metadata/namespace 
  kind: Ingress 
- path: metadata/labels/
  kind: Deployment 
- path: spec/template/spec/containers/env/valueFrom/secretKeyRef/name
  kind: Deployment
- path: stringData/redis-addr
  kind: Secret
