apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:
  app: engine
generators:
  - generators
transformers:
  - all-transformers
images:
- name: qlik-docker-qsefe.bintray.io/engine
  newName: $(IMAGE_REGISTRY)/engine
configurations:
  - ../../namereference.yaml
