apiVersion: qlik.com/v1
kind: SearchReplace
metadata:
  name: prefix
target:
  kind: SuperSecret
path: /
search: \$\(PREFIX\)
replaceWithObjRef:
  objref:
    apiVersion: qlik.com/v1
    kind: SuperSecret
    name: keycloak-secrets
  fieldref:
    fieldpath: metadata.labels.release