apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:
  app: keycloak
namespace: keycloak
resources:
  - resources-1
  - resources-2
  - ingress-controller
  - keycloak-certificate
transformers:
# - keycloak-certificate/vars
- vars
#- resources-2/vars
# - keycloak-certificate/modified-base-transformer