apiVersion: qlik.com/v1
kind: SelectivePatch
metadata:
  name: elastic-infra
enabled: true
patches:
  - path: server-snippet.yaml
    target:
      kind: Ingress
  - path: deploymentJSON.yaml
    target:
      kind: Deployment
  - patch: '[{ "op": "remove", "path": "/spec/clusterIP"}]'
    target:
      kind: Service
      name: elastic-infra-nginx-ingress-controller
  - patch: '[{ "op": "remove", "path": "/spec/clusterIP"}]'
    target:
      kind: Service
      name: elastic-infra-nginx-ingress-controller-metrics
