apiVersion: apps/v1
kind: Deployment
metadata:
  name: hub 
spec:
  template:
    spec:
      containers:
      - name: main
        imagePullPolicy: IfNotPresent
        resources:
          limits:
            cpu: "0"
            memory: "0"
          requests:
            cpu: "0"
            memory: "0"
