apiVersion: qlik.com/v1
kind: SelectivePatch
metadata:
  name: hub
enabled: true
patches:
  - path: patches/deploymentJSON.yaml
    target:
      kind: Deployment
      name: hub 
  - path: patches/deployment.yaml
