apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: data-prep
spec:
  template:
    spec:
      containers:
      - name: main
        imagePullPolicy: IfNotPresent
        command:
        - /bin/sh
        - -c
        - |
          export ENGINEADDRESS=`echo $(QIX_SESSIONS_URI)| cut -d'/' -f3 | cut -d':' -f1`
          export ENGINEPORT=`echo $(QIX_SESSIONS_URI)| cut -d':' -f3 | cut -d'/' -f1`
          export DATAFILESHOST=`echo $(DATA_FILES_URI)| cut -d'/' -f3 | cut -d':' -f1`
          export DATAFILESPORT=`echo $(DATA_FILES_URI)| cut -d':' -f3 | cut -d'/' -f1`
          export QIXDATAFILESHOST=`echo $(QIX_DATA_FILES_URI)| cut -d'/' -f3 | cut -d':' -f1`
          export QIXDATAFILESPORT=`echo $(QIX_DATA_FILES_URI)| cut -d':' -f3 | cut -d'/' -f1`
          export PRECEDENTSHOST=`echo $(PRECEDENTS_URI)| cut -d'/' -f3 | cut -d':' -f1`
          export PRECEDENTSPORT=`echo $(PRECEDENTS_URI)| cut -d':' -f3 | cut -d'/' -f1`
          ./start.sh
        env:
        - $patch: delete
          name: DPS_REDIS_URL
        - name: REDIS_URI
          valueFrom:
            configMapKeyRef:
              name:  data-prep-configs
              key:  redisUri
        - name: DPS_REDIS_URL
          value: $(REDIS_URI)
        - $patch: delete
          name: DPS_REDIS_PASSWORD
        - name: REDIS_PASSWORD
          valueFrom:
            secretKeyRef:
              name:  data-prep-secrets
              key:  redisPassword
        - name: DPS_REDIS_PASSWORD
          value: $(REDIS_PASSWORD)
        - $patch: delete
          name: AUTH_JWKS_URI
        - name: KEYS_URI
          valueFrom:
            configMapKeyRef:
              key: keysUri
              name: data-prep-configs
        - name: AUTH_JWKS_URI
          value: $(KEYS_URI)/keys/qlik.api.internal
        - $patch: delete
          name: FEATURE_FLAG_URL
        - name: FEATURE_FLAGS_URI
          valueFrom:
            configMapKeyRef:
              key: featureFlagsUri
              name: data-prep-configs
        - name: FEATURE_FLAG_URL
          value: $(FEATURE_FLAGS_URI)/v0/features
        - $patch: delete
          name: SPACES_URI
        - name: SPACES_URI
          valueFrom:
            configMapKeyRef:
              key: spacesUri
              name: data-prep-configs
        - $patch: delete
          name: ENGINEADDRESS
        - $patch: delete
          name: DATAFILESHOST
        - $patch: delete
          name: QIXDATAFILESHOST
        - $patch: delete
          name: PRECEDENTSHOST
        - $patch: delete
          name: ENGINEPORT
        - $patch: delete
          name: DATAFILESPORT
        - $patch: delete
          name: QIXDATAFILESPORT
        - $patch: delete
          name: PRECEDENTSPORT
        - name: QIX_SESSIONS_URI
          valueFrom:
            configMapKeyRef:
              key: qixSessionsUri
              name: data-prep-configs
        - name: DATA_FILES_URI
          valueFrom:
            configMapKeyRef:
              key: dataFilesUri
              name: data-prep-configs
        - name: QIX_DATA_FILES_URI
          valueFrom:
            configMapKeyRef:
              key: qixDataFilesUri
              name: data-prep-configs
        - name: PRECEDENTS_URI
          valueFrom:
            configMapKeyRef:
              key: precedentsUri
              name: data-prep-configs