varReference:
- path: metadata/annotations/nginx.ingress.kubernetes.io\/auth-url
  kind: Ingress
- path: metadata/annotations/kubernetes.io\/ingress.class
  kind: Ingress
- path: metadata/namespace 
  kind: Ingress 
- path: metadata/labels/
  kind: Deployment
- path: metadata/name
  kind: Deployment
- path: spec/template/spec/containers/env/valueFrom/secretKeyRef/name
  kind: Deployment 
- path: spec/template/spec/containers/env/valueFrom/configMapKeyRef/name
  kind: Deployment
- path: spec/template/spec/volumes/secret/secretName
  kind: Deployment
- path: metadata/name
  kind: StatefulSet
- path: spec/template/spec/containers/env/valueFrom/secretKeyRef/name
  kind: StatefulSet
- path: spec/template/spec/containers/env/valueFrom/configMapKeyRef/name
  kind: StatefulSet
- path: metadata/name
  kind: Service 
- path: metadata/name
  kind: Ingress 
- path: spec/rules/http/paths/backend/serviceName
  kind: Ingress 
- path: metadata/name
  kind: Secret 
- path: stringData/redis-addr
  kind: Secret
- path: data/mongoDbUri
  kind: Secret
- path: stringData/mongoDbUri
  kind: Secret
- path: metadata/name
  kind: ConfigMap 
- path: data/pdsUri
  kind: ConfigMap
- path: data/natsUri
  kind: ConfigMap
- path: data/featureFlagsUri
  kind: ConfigMap
- path: data/keysUri
  kind: ConfigMap
- path: data/natsStreamingClusterId
  kind: ConfigMap
- path: data/tokenAuthUri
  kind: ConfigMap
