apiVersion: apps/v1
kind: Deployment
metadata:
  name: collections
spec:
  template:
    metadata:
      labels:
        collections-nats-client: null
    spec:
      containers:
      - name: main
        imagePullPolicy: IfNotPresent
        env:
        - name: TERMINATION_GRACE_PERIOD_SECONDS
          value: "30"
        - name: MONGODB_URI
          valueFrom:
            secretKeyRef:
              key: mongoDbUri
              name: collections-secrets
        - $patch: delete
          name: MONGO_URI
        - name: MONGO_URI
          value: $(MONGODB_URI)
        - $patch: delete
          name: PDS_URI
        - name: PDS_URI
          valueFrom:
            configMapKeyRef:
              key: pdsUri
              name: collections-configs
        - name: ACCESS_CONTROL_ENABLED
          value: "true"
        - name: AUTH_ENABLED
          value: "true"
        - $patch: delete
          name: AUTH_JWKS_URI
        - name: KEYS_URI
          valueFrom:
            configMapKeyRef:
              key: keysUri
              name: collections-configs
        - name: AUTH_JWKS_URI
          value: $(KEYS_URI)/keys/qlik.api.internal
        - name: LEGACY_ROUTER_ENABLED
          value: "false"
        - name: AUTH_JWT_AUD
          value: qlik.api.internal
        - name: AUTH_JWT_ISS
          value: qlik.api.internal
        - name: ROLLBAR_ENABLED
          value: "false"
        - name: MESSAGING_ENABLED
          value: "true"
        - $patch: delete
          name: NATS_ADDR
        - name: NATS_URI
          valueFrom:
            configMapKeyRef:
              key: natsUri
              name: collections-configs
        - name: NATS_ADDR
          value: $(NATS_URI)
        - name: NATS_CONNECT_WAIT_SECONDS
          value: null
        - $patch: delete
          name: NATS_STREAMING_CLUSTER_ID
        - name: NATS_STREAMING_CLUSTER_ID
          valueFrom:
            configMapKeyRef:
              key: natsStreamingClusterId
              name: collections-configs
        - name: NATS_STREAMING_CHANNEL
          value: system-events.engine.app
        - name: NATS_TOKEN_AUTH_ENABLED
          value: "true"
        - $patch: delete
          name: NATS_TOKEN_AUTH_PRIVATE_KEY
        - name: TOKEN_AUTH_PRIVATE_KEY
          valueFrom:
            secretKeyRef:
              key: tokenAuthPrivateKey
              name: collections-secrets
        - name: NATS_TOKEN_AUTH_PRIVATE_KEY
          value: $(TOKEN_AUTH_PRIVATE_KEY)
        - $patch: delete
          name: NATS_TOKEN_AUTH_KID
        - name: TOKEN_AUTH_PRIVATE_KEY_ID
          valueFrom:
            secretKeyRef:
              key: tokenAuthPrivateKeyId
              name: collections-secrets
        - name: NATS_TOKEN_AUTH_KID
          value: $(TOKEN_AUTH_PRIVATE_KEY_ID)
        - $patch: delete
          name: NATS_TOKEN_AUTH_URL
        - name: TOKEN_AUTH_URI
          valueFrom:
            configMapKeyRef:
              key: tokenAuthUri
              name: collections-configs
        - name: NATS_TOKEN_AUTH_URL
          value: $(TOKEN_AUTH_URI)/v1/internal-tokens
         # deleting ENV due to it getting a 'null' value
        - $patch: delete
          name: ENV
