apiVersion: qlik.com/v1
kind: SelectivePatch
metadata:
  name: collections
enabled: true
patches:
  - path: deploymentJSON.yaml
    target:
      kind: Deployment
      name: collections
  - path: deployment.yaml
