apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- ../../eks/configs
- ../../eks/secrets
- searchReplaceClientSecret.yaml
- searchReplaceQlikIDPHost.yaml
- searchReplaceQlikDomain.yaml
- searchReplaceRealmName.yaml
- searchReplacePrefix.yaml
# transformers:
#   - ../transformers