- op: replace
  path: /spec/template/spec/containers/0/name
  value: main
- op: replace
  path: /apiVersion
  value: apps/v1
- op: replace
  path: /spec/template/spec/volumes/0/configMap/name
  value: keys-configs