apiVersion: qlik.com/v1
kind: SelectivePatch
metadata:
  name: keys
enabled: true
patches:
  - path: deploymentJSON.yaml
    target:
      kind: Deployment
      name: keys
  - path: configsJSON.yaml
    target:
      kind: ConfigMap
      name: keys-configmap