apiVersion: qlik.com/v1
kind: SelectivePatch
metadata:
  name: dcaasRedisUri
  labels:
    key: dcaasRedisUri
enabled: true
patches:
- target:
    kind: Deployment
    name: "^(r(e(d(i(s(.)[^s]|$)|[^i]|$)|[^d]|$)|[^e]|$)|[^r])*$"
  patch: |-
    apiVersion: apps/v1
    kind: Deployment
    metadata:
      name: component
    spec:
      template:
        spec:
          containers:
          - name: main
            env:
            - name: REDIS_URI
              valueFrom:
                configMapKeyRef:
                  key: redisUri
                  name: dcaas-configs
