apiVersion: apps/v1
kind: Deployment
metadata:
  name: audit
spec:
  template:
    metadata:
      labels:
        audit-nats-client: null
    spec:
      containers:
      - name: main
        imagePullPolicy: IfNotPresent
        env:
        - $patch: delete
          name: PDS_URI
        - name: PDS_URI
          valueFrom:
            configMapKeyRef:
              key: pdsUri
              name: audit-configs
        - name: NATS_URI
          valueFrom:
            configMapKeyRef:
              key: natsUri
              name: audit-configs
        - $patch: delete
          name: FEATURE_FLAGS_URI
        - name: FEATURE_FLAGS_URI
          valueFrom:
            configMapKeyRef:
              key: featureFlagsUri
              name: audit-configs
        - name: MONGODB_URI
          valueFrom:
            secretKeyRef:
              key: mongoDbUri
              name: audit-secrets
        - name: KEYS_URI
          valueFrom:
            configMapKeyRef:
              key: keysUri
              name: audit-configs
        - name: TOKEN_AUTH_URI
          valueFrom:
            configMapKeyRef:
              key: tokenAuthUri
              name: audit-configs
        - $patch: delete
          name: NATS_STREAMING_CLUSTER_ID
        - name: NATS_STREAMING_CLUSTER_ID
          valueFrom:
            configMapKeyRef:
              key: natsStreamingClusterId
              name: audit-configs
        - $patch: delete
          name: TOKEN_AUTH_PRIVATE_KEY
        - name: TOKEN_AUTH_PRIVATE_KEY
          valueFrom:
            secretKeyRef:
              key: tokenAuthPrivateKey
              name: audit-secrets
        - name: TOKEN_AUTH_PRIVATE_KEY_ID
          valueFrom:
            secretKeyRef:
              key: tokenAuthPrivateKeyId
              name: audit-secrets
        - name: TOKEN_AUTH_KID
          value: $(TOKEN_AUTH_PRIVATE_KEY_ID)
        - name: TOKEN_AUTH_URL
          value: $(TOKEN_AUTH_URI)/v1/internal-tokens
        - name: NATS_SERVERS
          value: $(NATS_URI)
        - $patch: delete
          name: MONGO_URI
        - name: MONGO_URI
          value: $(MONGODB_URI)
        - $patch: delete
          name: AUTH_JWKS_URI
        - name: AUTH_JWKS_URI
          value: $(KEYS_URI)/keys/qlik.api.internal
