apiVersion: qlik.com/v1
kind: SelectivePatch
metadata:
  name: mongodb 
enabled: true
patches:
  - path: patches/deploymentJSON.yaml
    target:
      kind: Deployment
      name: mongodb 
  - path: patches/deployment.yaml
    target:
      kind: Deployment
      name: mongodb 
          
