apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:
  app: edge-auth
resources:
- ../../../../../generators/edge-auth
- ../../../secrets
- ../../../configs
transformers:
- ../secrets
- ../configs
- values.yaml
patches:
- target:
    kind: SuperSecret
  patch: |-
    - op: replace
      path: /metadata/name
      value: edge-auth-secrets
- target:
    kind: SuperConfigMap
  patch: |-
    - op: replace
      path: /metadata/name
      value: edge-auth-configs