apiVersion: qlik.com/v1
kind: HelmValues
metadata:
  name: edge-auth
releaseNamespace: $(NAMESPACE)
values:
  mongodb:
    enabled: false
    ssl: false
    sslValidate: false
    checkServerIdentity: false
  secrets:
    create: false
  nats:
    enabled: true
