apiVersion: qlik.com/v1
kind: SedOnPath
metadata:
  name: fixQnatsdConfRoutes
path: data/gnatsd.conf
regex:
  - s/nats\:\/\/messaging-nats-cluster\:6222/nats:\/\/\$\(PREFIX\)-messaging-nats-cluster:6222/g
