apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:
  app: data-connector-qwc
resources:
- ../../../../../generators/data-connector-qwc
- ../../../secrets
- ../../../configs
transformers:
- ../secrets
- ../configs
- values.yaml
patches:
- target:
    kind: SuperSecret
  patch: |-
    - op: replace
      path: /metadata/name
      value: data-connector-qwc-secrets
- target:
    kind: SuperConfigMap
  patch: |-
    - op: replace
      path: /metadata/name
      value: data-connector-qwc-configs