apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:
  app: licenses
resources:
- ../../../transformers
transformers:
- ../../../../../.operator/transformers
- ../../../../../configuration/transformers
#Disable all transformers except these
patches:
- target:
    labelSelector: >-
      key notin (
        ingressClass,
        tokenAuthUri,
        pdsUri,
        featureFlagsUri,
        ingressClass,
        ingressAuthUrl,
        natsStreamingClusterId,
        natsUri,
        keysUri,
        mongoDbUri
        )
  patch: |-
    - op: replace
      path: /enabled
      value: false
    - op: replace
      path: /default
      value: true
