apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: component
spec:
  template:
    spec:
      containers:
      - name: main
        env:
        - name: REDIS_PASSWORD
          valueFrom:
            secretKeyRef:
              key: redisPassword
              name: redis-secrets