apiVersion: apps/v1
kind: Deployment
metadata:
  name: sense-client
spec:
  template:
    metadata:
      labels:
        sense-client-nats-client: null 
    spec:
      volumes: null
      containers:
      - name: main
        imagePullPolicy: IfNotPresent