apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:
  app: eks
resources:
  - eks.yaml
transformers:
  - ../../../../../.operator/configs
  - ../../../../../configuration/configs