apiVersion: qlik.com/v1
kind: SelectivePatch
metadata:
  name: messaging-component-configs
enabled: true
patches:
- target:
    kind: SuperConfigMap
  patch: |-
    apiVersion: qlik.com/v1
    kind: SuperConfigMap
    metadata:
      name: messaging-configs
    data:
      keysUri: "http://$(PREFIX)-messaging-keys:8080/v1/keys/qlik.api.internal"
      natsUri: "nats://$(PREFIX)-messaging-nats-client:4222"
      natsStreamingClusterId: "$(PREFIX)-messaging-nats-streaming-cluster"
