apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:
  app: encryption
resources:
- ../../../../../generators/encryption
- ../../../secrets
- ../../../configs
transformers:
  - ../configs
  - ../secrets
  - values.yaml
patches:
- target:
    kind: SuperSecret
  patch: |-
    - op: replace
      path: /metadata/name
      value: encryption-secrets
- target:
    kind: SuperConfigMap
  patch: |-
    - op: replace
      path: /metadata/name
      value: encryption-configs