apiVersion: qlik.com/v1
kind: SelectivePatch
metadata:
  name: data-rest-source-component-configs
enabled: true
patches:
- target:
    kind: SuperConfigMap
  patch: |-
    apiVersion: qlik.com/v1
    kind: SuperConfigMap
    metadata:
      name: data-rest-source-configs