apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:
  app: collections
resources:
- ../../../transformers
transformers:
- ../../../../../.operator/transformers
- ../../../../../configuration/transformers
#Disable all transformers except these
patches:
- target:
    labelSelector: >-
      key notin (
        tokenAuthUri,
        pdsUri,
        ingressClass,
        ingressAuthUrl,
        natsStreamingClusterId,
        natsUri,
        keysUri,
        secretClientCertificates,
        hostClientCertificates,
        pvcClientCertificates,
        mongoDbUri
        )
  patch: |-
    - op: replace
      path: /enabled
      value: false
    - op: replace
      path: /default
      value: true
