apiVersion: qlik.com/v1
kind: SearchReplace
metadata:
  name: secrets-prefix
target:
  kind: Secret
path: /
search: \$\(PREFIX\)
replaceWithObjRef:
  objref:
    apiVersion: v1
    kind: Secret
  fieldref:
    fieldpath: metadata.labels.release