apiVersion: qlik.com/v1
kind: SearchReplace
metadata:
  name: cm2
target:
  kind: ConfigMap
path: /
search: \$\(PREFIX\)
replaceWithObjRef:
  objref:
    apiVersion: v1
    kind: ConfigMap
  fieldref:
    fieldpath: metadata.labels.release