apiVersion: apps/v1
kind: Deployment
metadata:
  name: feature-flags
spec:
  template:
    metadata:
      labels:
        feature-flags-nats-client: null
    spec:
      containers:
      - name: main
        imagePullPolicy: IfNotPresent
        env:
        - name: KEYS_URI
          valueFrom:
            configMapKeyRef:
              key: keysUri
              name: feature-flags-configs
        - $patch: delete
          name: JWKS_ENDPOINT
        - name: JWKS_ENDPOINT
          value: $(KEYS_URI)/keys/qlik.api.internal
