apiVersion: qlik.com/v1
kind: SelectivePatch
metadata:
  name: feature-flags
enabled: true
patches:
  - path: deploymentJSON.yaml
    target:
      kind: Deployment
      name: feature-flags
  - path: deployment.yaml
