apiVersion: cert-manager.io/v1alpha3
kind: Certificate
metadata:
  name: certificate
spec:
  secretName: $(PREFIX)-tls
  issuerRef:
    name: $(PREFIX)-issuer
  commonName: $(QLIKSENSE_FQDN)
  dnsNames:
  -  $(QLIKSENSE_FQDN)
