apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:
  app: keycloak-certificate
resources:
- ../../../../../base/configs
transformers:
- ../../configs/transformers
- ../../../../../base/transformers
patches:
- target:
    kind: SuperConfigMap
  patch: |-
    - op: replace
      path: /metadata/name
      value: keycloak-certificate-configs


