apiVersion: apps/v1
kind: Deployment
metadata:
  name: eventing
spec:
  template:
    metadata:
      labels:
        eventing-nats-client: null
    spec:
      volumes:
      - name: eventing-secret
        secret:
          secretName: eventing-secrets
          items:
            - key: tokenAuthPrivateKey
              path: jwtPrivateKey
      containers:
      - name: main
        imagePullPolicy: IfNotPresent
        env:
        - $patch: delete
          name: JWKS_ENDPOINT
        - name: KEYS_URI
          valueFrom:
            configMapKeyRef:
              key: keysUri
              name: eventing-configs
        - name: JWKS_ENDPOINT
          value: $(KEYS_URI)/keys/qlik.api.internal
        - $patch: delete
          name: KEY_ID
        - name: TOKEN_AUTH_PRIVATE_KEY_ID
          valueFrom:
            secretKeyRef:
              key: tokenAuthPrivateKeyId
              name: eventing-secrets
        - name: KEY_ID
          value: $(TOKEN_AUTH_PRIVATE_KEY_ID)
        - $patch: delete
          name: INTERNAL_TOKENS_RESOURCE
        - name: TOKEN_AUTH_URI
          valueFrom:
            configMapKeyRef:
              key: tokenAuthUri
              name: eventing-configs
        - name: INTERNAL_TOKENS_RESOURCE
          value: $(TOKEN_AUTH_URI)/v1
        - $patch: delete
          name: NATS_URL
        - name: NATS_URI
          valueFrom:
            configMapKeyRef:
              key: natsUri
              name: eventing-configs
        - name: NATS_URL
          value: $(NATS_URI)
        - $patch: delete
          name: NATS_CLUSTER_ID
        - name: NATS_STREAMING_CLUSTER_ID
          valueFrom:
            configMapKeyRef:
              key: natsStreamingClusterId
              name: eventing-configs
        - name: NATS_CLUSTER_ID
          value: $(NATS_STREAMING_CLUSTER_ID)

