apiVersion: qlik.com/v1
kind: SelectivePatch
metadata:
  name: eventing
enabled: true
patches:
  - path: deploymentJSON.yaml
    target:
      kind: Deployment
      name: eventing
  - path: deployment.yaml
