apiVersion: qlik.com/v1
kind: EnvUpsert
metadata:
  name: engineEnvUpdate-spacesUri
  labels:
    key: spacesUri
enabled: true
target:
  kind: Engine
  name: engine-reload
path: spec/podSpec/containers/env
env:
- name: SPACES_URI
  valueFrom:
    configMapKeyRef:
      key: spacesUri
      name: configs
