apiVersion: qlik.com/v1
kind: EnvUpsert
metadata:
  name: engineEnvUpdate-geoOperationsUri
  labels:
    key: geoOperationsUri
enabled: true
target:
  kind: Engine
  name: engine-reload
path: spec/podSpec/containers/env
env:
- name: GEO_OPERATIONS_URI
  valueFrom:
    configMapKeyRef:
      key: geoOperationsUri
      name: configs
