apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: data-connector-qwc
spec:
  template:
    spec:
      containers:
      - name: main
        imagePullPolicy: IfNotPresent
        volumeMounts: null
        env:
        - name: REDIS_URI
          valueFrom:
            configMapKeyRef:
              name: data-connector-qwc-configs
              key:  redisUri
        - $patch: delete
          name: QWC_REDIS_CONFIG_STRING
        - name: QWC_REDIS_CONFIG_STRING
          value: $(REDIS_URI)
        - name: REDIS_PASSWORD
          valueFrom:
            secretKeyRef:
              name: data-connector-qwc-secrets
              key:  redisPassword
        - $patch: delete
          name: QWC_REDIS_PASSWORD
        - name: QWC_REDIS_PASSWORD
          value: $(REDIS_PASSWORD)
      volumes: null
