apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:
  app: management-console
resources:
- ../../../../../generators/management-console
#- ../../../secrets
- ../../../configs
transformers:
#- ../secrets
#- ../configs
- values.yaml
patches:
# - target:
#     kind: SuperSecret
#   patch: |-
#     - op: replace
#       path: /metadata/name
#       value: management-console-secrets
- target:
    kind: SuperConfigMap
  patch: |-
    - op: replace
      path: /metadata/name
      value: management-console-configs

