apiVersion: qlik.com/v1
kind: SelectivePatch
metadata:
  name: chronos-worker
enabled: true
patches:
  - path: deploymentJSON.yaml
    target:
      kind: Deployment
      name: chronos-worker
  - path: deployment.yaml
