apiVersion: qlik.com/v1
kind: SearchReplace
metadata:
  name: prefix
target:
  labelSelector: app=identity-providers
path: /
search: \$\(PREFIX\)
replaceWithObjRef:
  objref:
    apiVersion: v1
    kind: ConfigMap
    mame: identity-providers-configs
  fieldref:
    fieldpath: metadata.labels.release