apiVersion: qlik.com/v1
kind: SelectivePatch
metadata:
  name: tenants-component-configs
enabled: true
patches:
- target:
    kind: SuperConfigMap
  patch: |-
    apiVersion: qlik.com/v1
    kind: SuperConfigMap
    metadata:
      name: tenants-configs
    data:
      natsUri: "nats://$(PREFIX)-tenants-messaging-nats-client:4222"
      natsStreamingClusterId: "$(PREFIX)-tenants-messaging-nats-streaming-cluster"
      featureFlagsUri: "http://$(PREFIX)-tenants-feature-flags:8080/v1"
      usersUri: "http://$(PREFIX)-tenants-users:8080/v1"
      licensesUri: "http://$(PREFIX)-tenants-licenses:9200/v1"
      tokenAuthUri: "http://$(PREFIX)-tenants-edge-auth:8080/v1"
      keysUri: "http://$(PREFIX)-tenants-keys:8080/v1/keys/qlik.api.internal"

        