apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:
  app: eventing
resources:
- ../../../../../generators/eventing
- ../../../secrets
- ../../../configs
transformers:
- ../secrets
- ../configs
- values.yaml
patches:
- target:
    kind: SuperSecret
  patch: |-
    - op: replace
      path: /metadata/name
      value: eventing-secrets
- target:
    kind: SuperConfigMap
  patch: |-
    - op: replace
      path: /metadata/name
      value: eventing-configs

