apiVersion: qlik.com/v1
kind: SelectivePatch
metadata:
  name: ingressClass
  labels:
    key: ingressClass
enabled: true
patches:
- target:
    kind: Ingress 
  patch: |-
    apiVersion: extensions/v1beta1
    kind: Ingress
    metadata:
      name: component
      annotations:
        kubernetes.io/ingress.class: $(INGRESS_CLASS)

