apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:
  app: qix-sessions
resources:
- ../../../../../generators/qix-sessions
# - ../../../configs
# transformers:
# - ../configs
transformers:
- values.yaml
