apiVersion: qlik.com/v1
kind: SelectivePatch
metadata:
  name: qix-sessions
enabled: true
patches:  
  - path: deploymentJSON.yaml
    target:
      kind: Deployment
  - path: deployment.yaml
    target:
      kind: Deployment
  - path: secrets.yaml
    target:
      kind: Secret
      name: qix-sessions-secrets*
  - path: configsJSON.yaml
    target:
      kind: ConfigMap
      name: qix-sessions-configmap
      