apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:
  app: certificate
resources:
- ../../../../base/configs
transformers:
- ../configs
- ../../../../base/transformers
- ../../keycloak/resources-2/generators/transformer
- searchReplacePrefixCM.yaml
patches:
- target:
    kind: SuperConfigMap
  patch: |-
    - op: replace
      path: /metadata/name
      value: certificate-configs


