apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- ../../eks/configs
- ../../eks/secrets
- searchReplaceRealmName.yaml
- searchReplaceClientSecret.yaml
- searchReplaceDefaultUserPassword.yaml
- searchReplaceIngressIDP.yaml
transformers:
- ../../../../gke-demo/transformers
