apiVersion: qlik.com/v1
kind: SelectivePatch
metadata:
  name: identity-providers-component-secrets-keycloak
enabled: true
patches:
- patch: |-
    apiVersion: qlik.com/v1
    kind: SuperSecret
    metadata:
      name: identity-providers-secrets
    stringData:
      clientSecret: "xxxx"
      idpConfigs: >-
        [
          {
            "realm": "$(REALM_NAME)",
            "claimsMapping": {
              "name": [
                "name",
                "preferred_username"
              ],
              "sub": [
                "preferred_username"
              ],
              "groups": [
                "groups"
              ]
            },
            "clientId": "edge-auth",
            "clientSecret": "$(CLIENT_SECRET)",
            "hostname": "$(QLIKSENSE_FQDN)",
            "discoveryUrl": "https://$(IDP_FQDN)/auth/realms/$(REALM_NAME)/.well-known/openid-configuration",
            "postLogoutRedirectUri": "https://$(QLIKSENSE_FQDN)/"
          }
        ] 
  target:
    kind: SuperSecret
    labelSelector: app=identity-providers
