apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:
  app: redis
resources:
- ../../../../../generators/redis
- configs
- secrets
transformers:
- ../secrets
- ../configs
- values.yaml
