apiVersion: qlik.com/v1
kind: EnvUpsert
metadata:
  name: engineEnvUpdate-tokenAuthUri
  labels:
    key: tokenAuthUri
enabled: true
target:
  kind: Engine
  name: engine-reload
path: spec/podSpec/containers/env
env:
  - name: TOKEN_AUTH_URI
    valueFrom:
      configMapKeyRef:
        key: tokenAuthUri
        name: configs
