apiVersion: apps/v1
kind: Deployment
metadata:
  name: data-connector-rest
spec:
  template:
    spec:
      containers:
      - name: main
        imagePullPolicy: IfNotPresent
        volumeMounts: null
      volumes: null