apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:
  app: qix-data-connection
resources:
- ../../../../../generators/qix-data-connection
- ../../../secrets
- ../../../configs
transformers:
- ../secrets
- ../configs
- values.yaml 
patches:
- target:
    kind: SuperSecret
  patch: |-
    - op: replace
      path: /metadata/name
      value: qix-data-connection-secrets
- target:
    kind: SuperConfigMap
  patch: |-
    - op: replace
      path: /metadata/name
      value: qix-data-connection-configs