apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:
  app: spaces
resources:
- ../../../../../generators/spaces
- ../../../secrets
- ../../../configs
transformers:
- ../secrets
- ../configs
- values.yaml 
patches:
- target:
    kind: SuperSecret
  patch: |-
    - op: replace
      path: /metadata/name
      value: spaces-secrets
- target:
    kind: SuperConfigMap
  patch: |-
    - op: replace
      path: /metadata/name
      value: spaces-configs