apiVersion: apps/v1
kind: Deployment
metadata:
  name: geo-operations
spec:
  template:
    metadata:
      labels:
        geo-operations-nats-client: null
    spec:
      containers:
      - name: main
        imagePullPolicy: IfNotPresent
        env:
        - $patch: delete
          name: FEATUREFLAG_URL
        - name: FEATURE_FLAGS_URI
          valueFrom:
            configMapKeyRef:
              key: featureFlagsUri
              name: geo-operations-configs
        - name: FEATUREFLAG_URL
          value: $(FEATURE_FLAGS_URI)
        - $patch: delete
          name: LICENSES_URL
        - name: LICENSES_URI
          valueFrom:
            configMapKeyRef:
              key: licensesUri
              name: engine-configs
        - name: LICENSES_URL
          value: $(LICENSES_URI)
        - $patch: delete
          name: EDGEAUTH_URL
        - name: TOKEN_AUTH_URI
          valueFrom:
            configMapKeyRef:
              key: tokenAuthUri
              name: geo-operations-configs
        - name: EDGEAUTH_URL
          value: $(TOKEN_AUTH_URI)
        - $patch: delete
          name: JWT_PRIVATE_KEY
        - name: TOKEN_AUTH_PRIVATE_KEY
          valueFrom:
            secretKeyRef:
              key: tokenAuthPrivateKey
              name: geo-operations-secrets
        - name: JWT_PRIVATE_KEY
          value: $(TOKEN_AUTH_PRIVATE_KEY)
        - $patch: delete
          name: JWT_KEY_ID
        - name: TOKEN_AUTH_PRIVATE_KEY_ID
          valueFrom:
            secretKeyRef:
              key: tokenAuthPrivateKeyId
              name: geo-operations-secrets
        - name: JWT_KEY_ID
          value: $(TOKEN_AUTH_PRIVATE_KEY_ID)