apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
vars:
  - name: NAMESPACE
    objref:
      apiVersion: v1
      kind: ConfigMap
      name: mongodb-configs 
    fieldref:
      fieldpath: metadata.namespace
  - name: PREFIX 
    objref:
      apiVersion: v1
      kind: ConfigMap 
      name: mongodb-configs 
    fieldref:
      fieldpath: metadata.labels.release
configurations:
  - ../../../base/varreference.yaml
resources:
  - ../../resources/mongodb
