apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:
  app: sense-client
resources:
- ../../../../../generators/sense-client
- ../../../configs
transformers:
- ../configs
- values.yaml 
patches:
- target:
    kind: SuperConfigMap
  patch: |-
    - op: replace
      path: /metadata/name
      value: space-client-configs