apiVersion: apps/v1
kind: Deployment
metadata:
  name: policy-decisions
spec:
  template:
    spec:
      volumes: null
      containers:
      - name: main
        imagePullPolicy: IfNotPresent
        env:
        - name: MONGODB_URI
          valueFrom:
            secretKeyRef:
              key: mongoDbUri
              name: policy-decisions-secrets
        - $patch: delete
          name: MONGO_URI
        - name: MONGO_URI
          value: $(MONGODB_URI)
        - name: KEYS_URI
          valueFrom:
            configMapKeyRef:
              key: keysUri
              name: policy-decisions-configs
        - $patch: delete
          name: JWKS_ENDPOINT
        - name: JWKS_ENDPOINT
          value: $(KEYS_URI)/keys/qlik.api.internal
        - name: SPACES_URI
          valueFrom:
            configMapKeyRef:
              key: spacesUri
              name: policy-decisions-configs
        - name: LICENSES_URI
          valueFrom:
            configMapKeyRef:
              key: licensesUri
              name: policy-decisions-configs
        - name: GROUPS_URI
          valueFrom:
            configMapKeyRef:
              key: groupsUri
              name: policy-decisions-configs
        - $patch: delete
          name: SPACES__URL
        - $patch: delete
          name: LICENSES__URL
        - $patch: delete
          name: GROUPS__URL
        - name: SPACES__URL
          value: $(SPACES_URI)
        - name: LICENSES__URL
          value: $(LICENSES_URI)
        - name: GROUPS__URL
          value: $(GROUPS_URI)/v1