apiVersion: apps/v1
kind: Deployment
metadata:
  name: spaces
spec:
  template:
    metadata:
      labels:
        spaces-nats-client: null
    spec:
      containers:
      - name: main
        imagePullPolicy: IfNotPresent
        env:
        - name: FEATURE_FLAGS_URI
          valueFrom:
            configMapKeyRef:
              key: featureFlagsUri
              name: spaces-configs
        - name: MONGODB_URI
          valueFrom:
            secretKeyRef:
              key: mongoDbUri
              name: spaces-secrets
        - $patch: delete
          name: QUOTAS_URI
        - name: QUOTAS_URI
          valueFrom:
            configMapKeyRef:
              key: quotasUri
              name: spaces-configs
        - name: PDS_URI
          valueFrom:
            configMapKeyRef:
              key: pdsUri
              name: spaces-configs
        #  AUTH_JWKS_URI -> KEYS_URI
        - $patch: delete
          name: AUTH_JWKS_URI
        - name: KEYS_URI
          valueFrom:
            configMapKeyRef:
              key: keysUri
              name: spaces-configs
        - name: AUTH_JWKS_URI
          value: $(KEYS_URI)/keys/qlik.api.internal
        #  TOKEN_URI -> TOKEN_AUTH_URI
        - $patch: delete
          name: TOKEN_URI
        - name: TOKEN_AUTH_URI
          valueFrom:
            configMapKeyRef:
              key: tokenAuthUri
              name: spaces-configs
        - name: TOKEN_URI
          value: $(TOKEN_AUTH_URI)/v1/internal-tokens
        #  ACCESS_CONTROL_PDS_URI -> PDS_URI
        - $patch: delete
          name: ACCESS_CONTROL_PDS_URI
        - name: PDS_URI
          valueFrom:
            configMapKeyRef:
              key: pdsUri
              name: spaces-configs
        - name: ACCESS_CONTROL_PDS_URI
          value: $(PDS_URI)
        # GROUPS_CLIENT_URI -> GROUPS_URI
        - $patch: delete
          name: GROUPS_CLIENT_URI
        - name: GROUPS_URI
          valueFrom:
            configMapKeyRef:
              key: groupsUri
              name: spaces-configs
        - name: GROUPS_CLIENT_URI
          value: $(GROUPS_URI)
        # MESSAGING_NATS_ADDR -> NATS_URI
        - $patch: delete
          name: MESSAGING_NATS_ADDR
        - name: NATS_URI
          valueFrom:
            configMapKeyRef:
              key: natsUri
              name: spaces-configs
        - name: MESSAGING_NATS_ADDR
          value: $(NATS_URI)
        # MESSAGING_STAN_CLUSTER_ID -> NATS_STREAMING_CLUSTER_ID
        - $patch: delete
          name: MESSAGING_STAN_CLUSTER_ID
        - name: NATS_STREAMING_CLUSTER_ID
          valueFrom:
            configMapKeyRef:
              key: natsStreamingClusterId
              name: spaces-configs
        - name: MESSAGING_STAN_CLUSTER_ID
          value: $(NATS_STREAMING_CLUSTER_ID)
        - $patch: delete
          name: TOKEN_PRIVATE_KEY
        - name: TOKEN_AUTH_PRIVATE_KEY
          valueFrom:
            secretKeyRef:
              key: tokenAuthPrivateKey
              name: spaces-secrets
        - name: TOKEN_PRIVATE_KEY
          value: $(TOKEN_AUTH_PRIVATE_KEY)
        - $patch: delete
          name: TOKEN_KID
        - name: TOKEN_AUTH_PRIVATE_KEY_ID
          valueFrom:
            secretKeyRef:
              key: tokenAuthPrivateKeyId
              name: spaces-secrets
        - name: TOKEN_KID
          value: $(TOKEN_AUTH_PRIVATE_KEY_ID)
        - $patch: delete
          name: MONGO_URI
        - name: MONGO_URI
          value: $(MONGODB_URI)
        - $patch: delete
          name: FEATURE_FLAGS_URI
        - name: FEATURES_RESOURCE
          value: $(FEATURE_FLAGS_URI)
        # deleting ENVIRONMENT due to it getting a 'null' value
        - $patch: delete
          name: ENVIRONMENT
