apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:
  app: keycloak
generators:
  - generators
transformers:
  - ../secrets/transformers
  - ../configs/transformers
  - ../../../../base/transformers/base
  - vars