apiVersion: qlik.com/v1
kind: SelectivePatch
metadata:
  name: messaging
enabled: true
patches:
- path: statefulSet-mainContainer-nats-streaming.yaml
  target:
    kind: StatefulSet
    name: messaging-nats-streaming
- path: statefulSet-mainContainer-nats.yaml
  target:
    kind: StatefulSet
    name: messaging-nats
- path: statefulSet-streaming-delete-args.yaml
  target:
    kind: StatefulSet
    name: messaging-nats-streaming
- path: statefulSet-streaming.yaml
  target:
    kind: StatefulSet
    name: messaging-nats-streaming
- path: statefulSet-nats.yaml
  target:
    kind: StatefulSet
    name: messaging-nats
