apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:
  app: groups
resources:
- ../../../transformers/tokenAuthUri
#- ../../../transformers/pdsUri
- ../../../transformers/featureFlagsUri
- ../../../transformers/ingressClass
- ../../../transformers/ingressAuthUrl
#- ../../../transformers/natsStreamingClusterId
#- ../../../transformers/natsUri
- ../../../transformers/keysUri
- ../../../transformers/clientCertificates
- ../../../transformers/mongoDbUri
- ../../../transformers/usersUri
transformers:
- ../../../../../.operator/transformers
- ../../../../../configuration/transformers
#patches:
# - target:
#      name: tokenAuthUri
#   patch: |-
#     - op: replace
#       path: /enabled
#       value: false
# - target:
#      name: pdsUri
#   patch: |-
#     - op: replace
#       path: /enabled
#       value: false
# - target:
#      name: featureFlagsUri
#   patch: |-
#     - op: replace
#       path: /enabled
#       value: false
# - target:
#      name: natsStreamingClusterId
#   patch: |-
#     - op: replace
#       path: /enabled
#       value: false
# - target:
#      name: natsUri
#   patch: |-
#     - op: replace
#       path: /enabled
#       value: false
# - target:
#      name: keysUri
#   patch: |-
#     - op: replace
#       path: /enabled
#       value: false
# - target:
#      name: natsStreamingClusterId
#   patch: |-
#     - op: replace
#       path: /enabled
#       value: false
# - target:
#      name: ingressClass
#   patch: |-
#     - op: replace
#       path: /enabled
#       value: true
# - target:
#      name: secretClientCertificates
#   patch: |-
#     - op: replace
#       path: /enabled
#       value: true
 
